### ISSUE TITLE
Add Korean and Japanese speech to text

### ISSUE THREAD

**Issue by Dnkhatri** [patui/Nosub#2]
Please add japanese and korean speech to text.

**Comment by patui** [comment]
The software already supports

step1：Open Nosub

step2：Choose Google Engine
![01](https://user-images.githubusercontent.com/3607466/87868155-ef5fe180-c9c5-11ea-9166-0af2e04edd1e.jpg)


step3：Open Config.ini
![02](https://user-images.githubusercontent.com/3607466/87868163-f8e94980-c9c5-11ea-95bf-08b7a0a069e1.jpg)


step4：Modify language settings

**japanese** change into   `ja-JP`
**korean**    change into  `ko-KR`

![03](https://user-images.githubusercontent.com/3607466/87868167-0272b180-c9c6-11ea-8657-db3891f3f79a.jpg)

You can refer to this
https://www.google.com/intl/en/chrome/demos/speech.html
![04](https://user-images.githubusercontent.com/3607466/87868187-23d39d80-c9c6-11ea-98bb-40234e7ffa13.jpg)


step5：Restart the software

**Comment by Dnkhatri** [comment]
thks
