### ISSUE TITLE
离线自动声音排轴能否可以设定参数值?

### ISSUE THREAD

**Issue by siyexa2951** [patui/Nosub#3]
如声音的空白间隔之内多少不断行
以及音量多少以上不断行
还有同一行最多几个字便强迫断行

比如说 人的说话 同一行有时也会有停顿与呢喃
"今天刚好有个..这个..新闻"
以目前的版本 这个同一行的文字 会被断成三行
今天刚好有个
这个
新闻

也有人的说话很快速 霹雳啪拉说个不停
字幕的同一行就会变得很长 造成阅读上的困难

这两个问题
都会让自动断行在事後修正时间增加许多

另外 可以新增一个 自动剪掉无声片段并输出成XML的功能吗?
将视频里没有讲话的部份自动剪除
(也可设定参数值 低於多少分贝以下剪除 
 剪除的缓出入时间 少於几毫秒以内的空白不剪除等等)
剪除後合并 并输出为xml 供剪视频软件使用

**Comment by patui** [comment]
非常感谢你的反馈。

第一个问题：
目前音频切割算法的确还很初级，我会在beta9版本左右处理这个问题，beta7版本会改善这个问题，beta7会加入讯飞/阿里的文件转写功能。

第二个问题：
我电脑之前一直没有安装pr等剪辑工具，稍后我安装下，研究下导入pr的规则，以及xml的生成规则，怎么方便pr用户，这个功能可以做，我会尽快添加进去，视频剪辑的部分，我要看下。

**Comment by patui** [comment]
关于设定参数的问题，包括多少分贝，多少静音，当时我在做音频切割的时候有考虑，这些对用户太复杂，设计的原则是，给用户最优选项，不然用户会选择困难，用户会在这上面浪费时间，简单说，这是算法问题，程序的问题，不是用户的问题，如果开放设置给用户，这是技术妥协，简单说，这应该是开发者来解决的，不是推给用户去调试。

**Comment by siyexa2951** [comment]
感恩，谢谢你在这些功能上的付出与辛劳，很荣幸可以跟你讨论软件的发展
离线处理就算只有分行 能多省一部份时间也就足够感谢了
(因为一些朋友圈影片是比较个人的 目前不太偏好使用在线API处理的功能)

PR目前可导入XML 其一应该为FCPXML 7.0 的格式 (汇出的XML则不同格式)若需要研究
或许https://github.com/SubtitleEdit/subtitleedit 的另存格式上可以观摩
不知道有没有帮助 还是先提供给你参考

若是觉得这样分割影片汇出XML的功能与nosub的未来发展方向不同
也可自成为另一个软件也行

(题外话
若未来能搞清PR在汇出/汇入时的XML格式 说不定之後还可以做出
将PR中文字工具做出来的文字字幕 汇出转档为SRT或ASS的功能
(目前网路上的软件 顶多能做到单向 也就是SRT透XML汇入至PR 以转为文字工具的字幕))

会有这样的需求 是因为现在的自媒体发达
许多视频的剪辑会剪去无说话的部份 达到重点观看的效果
(如bilibili上的UP主开箱)
但需耗费大量时间人工剪除 不如直接由算法去处理片段以节省时间
使用PR剪辑的up主甚多 若此功能能问市 推广後想必有一定的使用率吧?

而使用XML或其他pr可汇入的文件档的好处
就在於汇入後仍可视情况再视调整各段的视频长度

至於参数设定，你说的这样的考量是好的
若算法达到极致 也就不需要参数设定了
不过 反观adobe的 ps 或是au、ae
里头许多特效跟处理 除了预设好的范本可选择外
也提供了详细设定参数的选项
这倒是一种两全的作法
对於最优选项提供了几个范本可套用 
对於要硬核调整的用户 给予调整参数的方式
可以参考一下

由於目前PR没有这个功能
我给一下在水管上的其他软件视频连结
希望对一些参数设定上的规划有帮助

这个是Vegas  後期剪辑软件中 关於自动移除静音的功能
但是分开跟贴紧是两个功能 不是一键完成 好处是自由度高 可以参考一下
https://www.youtube.com/watch?v=T_8e650vYxA

这是比较简单的後期剪辑软件
有自动切出静音 但没删除後贴紧一起的功能
https://www.youtube.com/watch?v=jONnIi94W94

这是au上面 关於自动移除静音 不过仅限音频 但其设定选项可供参考
https://www.youtube.com/watch?v=HTCVEE2xfFA

**Comment by patui** [comment]
此功能在V2版本已经去掉了，敬请关注V2新版，V2带来了大量新特性；
