### ISSUE TITLE
如何导出软件字幕

### ISSUE THREAD

**Issue by Jasonltz** [patui/Nosub#35]
Hello Patui, 

你好，我想问如何导出capcut （剪映海外版）手机软件的外语的字幕，比如日语韩语字幕。因为之前有使用SpeechJsonParser插件而可以顺利导出剪映的字幕。因此想问你要如何在插件内设定capcut以便在在emulator里面导出字幕，不知你可以协助？谢谢

**Comment by patui** [comment]
有空可以看看哦，因为我这边没有按照过海外版，周末我看看，如果可以我帮你加上去。

**Comment by Jasonltz** [comment]
十分谢谢你的协助。
此外，想问你比如我和朋友导出了这一份文件，我们要如何把它转换成srt 格式呢？之前朋友反馈说用了一些方法似乎也不能正常转换。
[File.txt](https://github.com/patui/Nosub/files/7078240/File.txt)

**Comment by patui** [comment]
> 十分谢谢你的协助。
> 此外，想问你比如我和朋友导出了这一份文件，我们要如何把它转换成srt 格式呢？之前朋友反馈说用了一些方法似乎也不能正常转换。
> [File.txt](https://github.com/patui/Nosub/files/7078240/File.txt)

可以转换，这个应该就是剪映返回的json文件，稍微处理一下就可以转换为srt文件哦。

**Comment by Jasonltz** [comment]
你好，我们也进行转换，可是最后导出的srt 所嵌入的时间点timestamp 都不准确了，不知你可以分享有什么软件可以准确转化timestamp 吗？谢谢协助

**Comment by patui** [comment]
> 十分谢谢你的协助。
> 此外，想问你比如我和朋友导出了这一份文件，我们要如何把它转换成srt 格式呢？之前朋友反馈说用了一些方法似乎也不能正常转换。

这里有一个我用C#写的JSON文件转SRT工具，之前写的，选择剪映，然后点击转化。
我这边好像代理出了点问题，如果你这边可以可以抓到请求结果的URL发给我，我可以加入到SpeechJsonParser插件；

![image](https://user-images.githubusercontent.com/3607466/132090675-0cb72a3d-e5fc-4d74-88cf-dd16f189435c.png)

https://nosub.lanzoui.com/iV4Iktln84f
