### ISSUE TITLE
aliyun转写闪退问题

### ISSUE THREAD

**Issue by ainy0315** [patui/Nosub#36]
我配置好key和secret 以及云存储后运行nosub语音转写出现闪退，讯飞和腾讯没有任何问题
再次打开提示语音任务失败

**Comment by patui** [comment]
> 我配置好key和secret 以及云存储后运行nosub语音转写出现闪退，讯飞和腾讯没有任何问题 再次打开提示语音任务失败

是必然出现的吗，提示的语音任务失败有原因吗。

**Comment by patui** [comment]
可以看看阿里云对象存储OSS，文件有没有上传成功。

**Comment by ainy0315** [comment]
文件没有上传成功  提示创建任务成功 然后出现蓝色的小圆圈 就闪退了

**Comment by ainy0315** [comment]
> > 我配置好key和secret 以及云存储后运行nosub语音转写出现闪退，讯飞和腾讯没有任何问题 再次打开提示语音任务失败
> 
> 是必然出现的吗，提示的语音任务失败有原因吗。
对 不配置oss就会提示不存在 配置了oss就闪退了  buket name 填名称和bucket域名都会出现

**Comment by ainy0315** [comment]
> > 我配置好key和secret 以及云存储后运行nosub语音转写出现闪退，讯飞和腾讯没有任何问题 再次打开提示语音任务失败
> 
> 是必然出现的吗，提示的语音任务失败有原因吗。

必然出现   没提示原因  创建任务成功后就闪退了

**Comment by ainy0315** [comment]
![QQ截图20220108221126](https://user-images.githubusercontent.com/45345418/148647414-84af20fb-834a-4126-9bd2-0a0119b09c22.png)
![QQ截图20220108221224](https://user-images.githubusercontent.com/45345418/148647416-06f31840-d065-49d0-93ec-ae507d0722b7.png)

**Comment by patui** [comment]
软件现在没有加入任何异常处理，包括写入日志，这个问题，后面我联系您，这段时候我不太方便处理，刚好最近我生病了。

**Comment by patui** [comment]
非常感谢您的反馈，后面我会尝试联系您。

**Comment by patui** [comment]
> 软件现在没有加入任何异常处理，包括写入日志，这个问题，后面我联系您，这段时候我不太方便处理，刚好最近我生病了。

没有全局异常捕捉的问题，后面我会加入。

**Comment by ainy0315** [comment]
> > 软件现在没有加入任何异常处理，包括写入日志，这个问题，后面我联系您，这段时候我不太方便处理，刚好最近我生病了。
> 
> 没有全局异常捕捉的问题，后面我会加入。

感谢大佬滴回复

**Comment by ainy0315** [comment]
> > 软件现在没有加入任何异常处理，包括写入日志，这个问题，后面我联系您，这段时候我不太方便处理，刚好最近我生病了。
> 
> 没有全局异常捕捉的问题，后面我会加入。

我发现腾讯语音也总是是同样的问题  百度我没测试 目前讯飞可以正常工作 请问是否除了讯飞都会调用阿里云存储啊

**Comment by patui** [comment]
> > > 软件现在没有加入任何异常处理，包括写入日志，这个问题，后面我联系您，这段时候我不太方便处理，刚好最近我生病了。
> > 
> > 
> > 没有全局异常捕捉的问题，后面我会加入。
> 
> 我发现腾讯语音也总是是同样的问题 百度我没测试 目前讯飞可以正常工作 请问是否除了讯飞都会调用阿里云存储啊

腾讯语音超过5MB也会调用阿里云语音，你加下Nosub QQ群：870178887吧，我明天远程看看。

**Comment by ainy0315** [comment]
> > > > 软件现在没有加入任何异常处理，包括写入日志，这个问题，后面我联系您，这段时候我不太方便处理，刚好最近我生病了。
> > > 
> > > 
> > > 没有全局异常捕捉的问题，后面我会加入。
> > 
> > 
> > 我发现腾讯语音也总是是同样的问题 百度我没测试 目前讯飞可以正常工作 请问是否除了讯飞都会调用阿里云存储啊
> 
> 腾讯语音超过5MB也会调用阿里云语音，你加下Nosub QQ群：870178887吧，我明天远程看看。

找到问题了 云存储enpoint没添加https头 ...

**Comment by ainy0315** [comment]
谢谢大佬

**Comment by patui** [comment]
> 我下周看看。

**Comment by patui** [comment]
已经去掉了在线语音识别的功能，可以期待一下新版；
