### ISSUE TITLE
语音任务失败

### ISSUE THREAD

**Issue by ririkashoppi** [patui/Nosub#39]
WinHttpReceiveResponse: 12152: 服务器返回的信息无效或不可识别

**Comment by patui** [comment]
这种应该是识别失败了吧，有音频文件吗，可以发我测试下；
或是在QQ群反馈：870178887

**Comment by patui** [comment]
> WinHttpReceiveResponse: 12152: 服务器返回的信息无效或不可识别

告知语音识别引擎，
另外换个视频看看是否有同样的问题，简单说看下是否必然出现的。

**Comment by patui** [comment]
在线语音识别的功能已经砍掉。
