### ISSUE TITLE
蓝奏云 无法下载

### ISSUE THREAD

**Issue by yuehouqiyou** [patui/Nosub#48]
蓝奏云 无法下载，希望增加其他下载方式

**Comment by patui** [comment]
去官网的入口下载看看。

**Comment by yuehouqiyou** [comment]
> 去官网的入口下载看看。

去了。最新β版 官网不也是蓝奏云吗

**Comment by patui** [comment]
> > 去官网的入口下载看看。
> 
> 去了。最新β版 官网不也是蓝奏云吗

你那边蓝奏云下载不了吗。

**Comment by patui** [comment]
> 蓝奏云 无法下载，希望增加其他下载方式

我周日在GitHub附件上传上去，也重新发个版本。

**Comment by yuehouqiyou** [comment]
> > 蓝奏云 无法下载，希望增加其他下载方式
> 
> 我周日在GitHub附件上传上去，也重新发个版本。

ok

**Comment by patui** [comment]
好了，beta11已经发布了，https://github.com/patui/Nosub/releases/tag/2.0beta11
