### ISSUE TITLE
0xc000142 请问缺少什么库?

### ISSUE THREAD

**Issue by lijileiGood** [patui/Nosub#49]
win11, 请问我电脑上缺了什么库? 
能否给个安装连接之类的
<img width="312" alt="Snipaste_2024-01-15_17-52-44" src="https://github.com/patui/Nosub/assets/44024086/1997d6cc-bde0-4f3a-bad2-ca9d0584125c">
![Snipaste_2024-01-15_17-53-01](https://github.com/patui/Nosub/assets/44024086/b3ce6bbd-d0a5-4176-8bbb-f93d9dc4a5da)

**Comment by patui** [comment]
我明天看看，我在虚拟机跑过Win11啊，会尽快回复。

**Comment by lijileiGood** [comment]
巧了, 我说一下详细的信息,  我也也是虚拟机
本地电脑是: 2020款 m1 macbook pro
虚拟软件是: parallels desktop
win11版本
<img width="469" alt="image" src="https://github.com/patui/Nosub/assets/44024086/2c1c5827-2a31-4f8e-8041-cf2bf179224b">

复现环境吧: 这个虚拟机没瞎搞过,比较原生,  只会用来跑一些win专有的软件

昨天发完issue我又实验了一下
1. 真正的win11物理机, ok, 同事的, 没细看版本
2. V1最后一个版本是ok的

应该是缺少某个库导致的, 但win11的控制面板只显示安装的软件, 像以前的.netxxx等等都不显示了

我也不是搞win平台的, 所以还是麻烦你确认一下那个库导致的吧?

**Comment by patui** [comment]
我一会全新安装一个win11的虚拟机看看。

**Comment by patui** [comment]
https://helpdeskgeek.com/how-to/how-to-fix-the-application-was-unable-to-start-correctly-0xc0000142-error-in-windows/

这里有一个解决这个报错的思路，你可以参考一下，
建议操作前做一个虚拟机快照。

**Comment by patui** [comment]
> 我一会全新安装一个win11的虚拟机看看。

@lijileiGood 我刚才新建了一个win11镜像，系统安装完毕后，没有安装其他软件，正常运行。

![win11-bug-X142](https://github.com/patui/Nosub/assets/3607466/42199f78-e5b8-470b-a283-4c6cbba920e6)

**Comment by lijileiGood** [comment]
on my god, 我放弃啦.
- 可能是苹果M芯片的事, 我就不再测试啦
- 也可能是虚拟机安装软件的事

## 详细测试步骤
1. 更新所有的系统更新, 失败
2. 安装楼上说的 c++库 https://aka.ms/vs/17/release/vc_redist.x64.exe, 失败
  - 但图标变成正常了, 但被下面的步骤又搞成坏了
3. 根据链接, run admin 失败
4. 根据链接, run win7, fail
5. 根据链接, download .net8 sdk, fail.  
   - in url is download .net6, but 考虑到高版本向下兼容, so download .net8
 6. restart , fail 
 7. 根据链接, download DirectX, fail
     - 这个玩意我没听说过, 最终安装到最后其实是一个大概fail的消息提示, 没截图
     - 也就是这个玩意把第二步说图标正常后, 又给搞坏了
  8. restart , fail

thank you very much

**Comment by patui** [comment]
这个问题有可能是我混用了vc和mingw的库导致的，今年的v3版本我来看看。

**Comment by patui** [comment]
> 巧了, 我说一下详细的信息, 我也也是虚拟机 本地电脑是: 2020款 m1 macbook pro 虚拟软件是: parallels desktop win11版本 <img alt="image" width="469" src="https://private-user-images.githubusercontent.com/44024086/296901590-2c1c5827-2a31-4f8e-8041-cf2bf179224b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NDA4MzI5MDAsIm5iZiI6MTc0MDgzMjYwMCwicGF0aCI6Ii80NDAyNDA4Ni8yOTY5MDE1OTAtMmMxYzU4MjctMmEzMS00ZjhlLTgwNDEtY2YyYmYxNzkyMjRiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTAzMDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwMzAxVDEyMzY0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE0Yzk3ZTk2M2NlYWZhMzc4OTlhMzZjNjlhNmM1YTFhZjZhODg4ZTg5Zjc5YjRhNjI5MzkwMDMyMjQwOGUwMjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.1QhPVL7-wl-RkcC-_wRRKYzAZex7hxOatxKAw2TgxCs">
> 
> 复现环境吧: 这个虚拟机没瞎搞过,比较原生, 只会用来跑一些win专有的软件
> 
> 昨天发完issue我又实验了一下
> 
> 1. 真正的win11物理机, ok, 同事的, 没细看版本
> 2. V1最后一个版本是ok的
> 
> 应该是缺少某个库导致的, 但win11的控制面板只显示安装的软件, 像以前的.netxxx等等都不显示了
> 
> 我也不是搞win平台的, 所以还是麻烦你确认一下那个库导致的吧?

macos的版本已经发布了，不需要在虚拟机体验了，可以在m芯片上体验nosub了。

**Comment by patui** [comment]
> win11, 请问我电脑上缺了什么库? 能否给个安装连接之类的 <img alt="Snipaste_2024-01-15_17-52-44" width="312" src="https://private-user-images.githubusercontent.com/44024086/296718365-1997d6cc-bde0-4f3a-bad2-ca9d0584125c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NDA4MzI5MDAsIm5iZiI6MTc0MDgzMjYwMCwicGF0aCI6Ii80NDAyNDA4Ni8yOTY3MTgzNjUtMTk5N2Q2Y2MtYmRlMC00ZjNhLWJhZDItY2E5ZDA1ODQxMjVjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTAzMDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwMzAxVDEyMzY0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTAxMjJlZjExNWVkYTY3N2M1MTdlYzE2NDAzYWU0OTc1YzM1MWI5MDVmMmY1ZWI3YjhkMzllYzQ3ZDEwNTRhMDgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.xL-v9OteDzEgtOPBgqvu_SK7D1dwfF2HCeM5jHsanp4"> ![Snipaste_2024-01-15_17-53-01](https://github.com/patui/Nosub/assets/44024086/b3ce6bbd-d0a5-4176-8bbb-f93d9dc4a5da)

已经统一了用msvc库了，可以再试试Windows版本，是否还有问题；

**Comment by LeoLeeTech** [comment]
感谢你的不懈努力!
目前我已无相关需求, 但仍可在此继续回复, 以飨后人
